language: cpp
cache: ccache
sudo: required
dist: trusty
services:
  - docker
os:
  - linux
env:
  - JOB=PRE_COMMIT

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
  ssh_known_hosts: 52.76.173.135
before_install:
  -  sudo pip install -U virtualenv pre-commit pip
  -  docker pull paddlepaddle/paddle:latest
script:
  -  .travis/precommit.sh
  -  docker run -i --rm -v "$PWD:/py_unittest" paddlepaddle/paddle:latest /bin/bash -c 
    'cd /py_unittest; sh .travis/unittest.sh'
  - .travis/deploy.sh
notifications:
  email:
    on_success: change
    on_failure: always
